# Generated by Django 5.0.7 on 2024-10-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_rename_user_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
    ]
