# Generated by Django 5.0.7 on 2024-10-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_rename_user_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
    ]
